### ISSUE TITLE
Milestone 1 submission prerequisites

### ISSUE THREAD

**Issue by sstanovnik** [IglooRental/igloorental#1]
- [x] Check the travis-dockerhub pipeline (build -> test -> deploy)
- [x] Do we have postgres closed off, but etcd and the microservices world-accessible? (clusterip and nodeport)
- [x] Do we have two health checks per service?
- [x] Does the health check return the appropriate status codes?
- [x] Make kubernetes monitor the health endpoint (`/health`)
- [x] Set `healthy` to false in the configuration (or use the `/v1/mgmt/sethealth` endpoint) and check if kubernetes detected that and spawned a new instance
- [x] Do we have exposed metrics?
- [x] Add Horizontal Pod Autoscaling to the kubernetes deployments
- [x] Load a service with `/v1/mgmt/load` and see if kubernetes spawns more instances
- [x] Insert the final cluster IP address **and ports** into the `/v1/mgmt/info` output.
- [x] Test whether the microservice endpoints, as specified in the info endpoint, actually work.

These checks need to be done on the **remote** kubernetes cluster (well, all of them, but these ones specifically):
- [x] Can we access the etcd server from the outside (use the configuration checker to check)
- [x] Does the configuration (`/v1/mgmt/config`) change on etcd value change

#### Notes
The etcd configuration does not exist when you first start the app - the values are read from the yaml file. The namespace (`/environments/dev/services/<service-name>/1.0.0/config/<config-name>/`) does exist however, and you just need to set the appropriate (translated, e.g. thisName -> this-name) value.

**Comment by sstanovnik** [comment]
This should have been closed a long time ago. Lel.
